# RPi# GPIO connections to the DAT and CLK pins on the HX711 IC
tmp102Address = 0x49 /# his is the 7-bit address of the TMP102. On OpenScale it has ADR0 tied to VCC.

# Internal EEPROM locations for user settings
LOCATION_MASS_UNITS                 =   0x01
LOCATION_REPORT_RATE_MSB            =   (LOCATION_MASS_UNITS + 1)
LOCATION_REPORT_RATE_LSB            =   (LOCATION_MASS_UNITS + 2)
LOCATION_CALIBRATION_FACTOR_MSB     =   (LOCATION_MASS_UNITS + 3)
LOCATION_CALIBRATION_FACTOR_MIDHIGH =   (LOCATION_MASS_UNITS + 4)
LOCATION_CALIBRATION_FACTOR_MIDLOW  =   (LOCATION_MASS_UNITS + 5)
LOCATION_CALIBRATION_FACTOR_LSB     =   (LOCATION_MASS_UNITS + 6)
LOCATION_BAUD_MSB	                  =   (LOCATION_MASS_UNITS + 7)
LOCATION_BAUD_MIDHIGH	              =   (LOCATION_MASS_UNITS + 8)
LOCATION_BAUD_MIDLOW	               =   (LOCATION_MASS_UNITS + 9)
LOCATION_BAUD_LSB        	          =   (LOCATION_MASS_UNITS + 10)
LOCATION_TARE_POINT_MSB             =   (LOCATION_MASS_UNITS + 11)
LOCATION_TARE_POINT_MIDHIGH         =   (LOCATION_MASS_UNITS + 12)
LOCATION_TARE_POINT_MIDLOW          =   (LOCATION_MASS_UNITS + 13)
LOCATION_TARE_POINT_LSB             =   (LOCATION_MASS_UNITS + 14)
LOCATION_TIMESTAMP_ENABLE           =   (LOCATION_MASS_UNITS + 15)
LOCATION_DECIMAL_PLACES             =   (LOCATION_MASS_UNITS + 16)
LOCATION_AVERAGE_AMOUNT             =   (LOCATION_MASS_UNITS + 17)
LOCATION_LOCAL_TEMP_ENABLE          =   (LOCATION_MASS_UNITS + 18)
LOCATION_REMOTE_TEMP_ENABLE         =   (LOCATION_MASS_UNITS + 19)
LOCATION_STATUS_ENABLE              =   (LOCATION_MASS_UNITS + 20)
LOCATION_SERIAL_TRIGGER_ENABLE      =   (LOCATION_MASS_UNITS + 21)
LOCATION_RAW_READING_ENABLE         =   (LOCATION_MASS_UNITS + 22)

# Arduino doesn't properly handle bauds lower than 500bps
BAUD_MIN = 1200
BAUD_MAX = 1000000